### ISSUE TITLE
How to apply this tool?

### ISSUE THREAD

**Issue by mdmanurung** [lucylgao/clusterpval#1]
Dear authors,

Thank you for writing this package. I could understand the motivation behind it, however, owing to my lack of in-depth knowledge in this area, I find it hard to imagine how to include this package in my existing scRNAseq analysis workflow.

The vignette showed how to test for the difference between two clusters. But then what should I do if I have 10 clusters? Does this mean that I should perform a pairwise comparison of all 10 clusters (10 choose 2 = 45 tests)? 

And if my p-value is above a certain threshold, can I use it to justify the merging of a pair of clusters?

Thanks for your insights.

Best,
Mikhael

**Comment by lucylgao** [comment]
Hi Mikhael, 

If you have 10 clusters and you are interested in the difference in means between all pairwise combinations of them, then you can certainly apply the test to all 10 choose 2 pairs of clusters, as long as you also use a multiple-testing correction like Bonferroni or Benjamini-Hochberg. 

If your p-value is above your pre-specified significance level, then there is little to no evidence that there is a difference in means between the two estimated clusters, so we do not reject the null hypothesis of no difference in means. Note that this is not the same as saying there is evidence that there is no difference in means, or accepting the null hypothesis! So there is no formal statistical justification for merging pairs of clusters based on a large p-value. 

Best, 
Lucy
