### ISSUE TITLE
Per-dimension difference in means

### ISSUE THREAD

**Issue by jonathanishhorowicz** [lucylgao/clusterpval#3]
Hi,

I am interested in using this interesting approach for post-clustering inference, but I need to test the difference in means in each dimension separately (for differential expression analysis).

Is this possible/appropriate using this method?

Thanks in advance!

**Comment by lucylgao** [comment]
Unfortunately, as of right now, no. We're hopeful that we can extend our methods to test for differences between one (or a subset of) features in the future, though!
