### ISSUE TITLE
Applying clusterpval in single cell data

### ISSUE THREAD

**Issue by ghost** [lucylgao/clusterpval#4]
Hi Lucy, 

I am interested in using your statistical model to test gene expression differences between clusters. 
My input is a matrix where: columns correspond to cells, rows to genes. Usually I would apply a (row-wise) wilcox test in order to check if the mean expression of one group of cells (belonging to a cluster) is significantly higher/lower than in the other group. This way, I can obtain a list of genes significantly up/down regulated between these two groups. 

I have been testing your clusterpval tool but I am not sure how to apply it in cases like this. Can you help me? 

Best, 
Coral

**Comment by lucylgao** [comment]
Hi Coral, please see my answer to a similar question here: https://github.com/lucylgao/clusterpval/issues/3
